import Head from 'next/head'
import Image from 'next/image'
import HeroCont from '../components/HeroCont'
import styles from '../styles/Home.module.css'
import Button from '../components/Button'
import SubButton from '../components/SubButton'
import RevCard from '../components/reviewCard'
import Header from '../components/Header'
import TopBar from '../components/topBAr'
import PopMenu from '../components/popMenu'
import reviews from '../data/reviews.json'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spill it.svg" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"/>

       
      </Head>

     <TopBar/>
     <PopMenu/>
    

      <main className={styles.main}>
        <HeroCont/>
        <Button />
        <Header />
        
        <div >
        {
          reviews.slice(0,5).map( (rev, index) => {
           return (
              <RevCard 
              key={index}
              name={rev.name}
              rating={`${rev.rating} stars`}
              review={`"${rev.review}"`}></RevCard>
            )
           })
          
        }
       </div>
        <SubButton bttntxt='see more...'/>
      </main>

  
    </div>
  )
}
