import Head from 'next/head'
import Image from 'next/image'
import HeroCont from '../components/HeroCont'
import styles from '../styles/Home.module.css'
import Button from '../components/Button'
import SubButton from '../components/SubButton'
import RevCard from '../components/reviewCard'
import Header from '../components/Header'
import TopBar from '../components/topBar'
import PopMenu from '../components/popMenu'
import reviews from '../data/reviews.json'
import Link from 'next/link'



export default function Home() {
  return (
    <div id="column" className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spill it.svg" />

       
      </Head>

     <TopBar/>
     <PopMenu/>
    

      <main className={styles.main} id="margins">
        <HeroCont/>

         <Button />
     
        
        <Header />
        
        <div id="flex">
        {
          reviews.slice(0,5).map( (rev, index) => {
           return (
              <RevCard 
              key={index}
              name={rev.name}
              rating={`${rev.rating} stars`}
              review={`"${rev.review}"`}></RevCard>
            )
           })
          
        }
       </div>
       <Link href="/findASpot">
         <SubButton  bttntxt='see more...' />
       </Link>
      
      </main>

  
    </div>
  )
}
