import Head from 'next/head'
import Image from 'next/image'
import HeroCont from '../components/HeroCont'
import styles from '../styles/Home.module.css'
import Button from '../components/Button'
import SubButton from '../components/SubButton'
import RevCard from '../components/reviewCard'
import Header from '../components/Header'
import TopBar from '../components/topBAr'
import PopMenu from '../components/popMenu'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spill it.svg" />
       
      </Head>

     <TopBar/>
     <PopMenu/>
    

      <main className={styles.main}>
        <HeroCont/>
        <Button />
        <Header />
        
        <RevCard/>
        <SubButton bttntxt='see more...'/>
      </main>

  
    </div>
  )
}
